name: flex_textfield_controller
description: flexible
homepage: https://github.com/monki1/flutter_Flex_TextField_Controller


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.1



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
